### ISSUE TITLE
Progression Missing and Misclassified Items

### ISSUE THREAD

**Issue by Mistermycelium** [OrianaVenture/VentureValheim#21]
Lox pelt, sharpening stone, egg, onion and turnips are missing from the list. Obsidian is inappropriately classified as a post swamp tech, locking players out from using loot in the crypts. It would be nice if the dictionaries were offloaded to a yaml file so that we could configure it ourselves, as there may be differences of opinion on where some items belong.

**Comment by OrianaVenture** [comment]
Thanks for the report,

* Eggs, onions, and turnips are on the list. It appears that the cooking lock wasn't working correctly with the cauldron so I will fix that.
* Lot pelts are missing, and blue jute, but I will add those in the next update.
* The sharpening stone is made from stone, so it was not locked in any way since stone is available without defeating any bosses. I will add in locking for that item specifically though until the elder is defeated since that is when you can access iron and the stonecutting bench.
* Obsidian I would classify as a mountain item, which gets unlocked after you defeat bonemass. I'm not sure where else you would be finding Obsidian before mountains? I will not be changing that at this time.

I would like to add in a way for players to customize the locking themselves, but that would be too much work for me to put in at this time. I will be considering that for a future update, and would likely have that feature completed by the time the game is fully released.

**Comment by OrianaVenture** [comment]
Resolved in the 0.2.0 update, please reopen if you have any more issues or questions: #584f31ffed5d1476d2693b07543520318379a778

**Comment by Mistermycelium** [comment]
Poison arrows cannot be used (crypt drop) due to obsidian being locked.
