### ISSUE TITLE
World Advancement Progression: Hildir quest

### ISSUE THREAD

**Issue by Mistermycelium** [OrianaVenture/VentureValheim#22]
With the recent update, players on my server lost the ability to track the Hildir quest individually and cannot regain access to the ability to purchase items from her.

**Comment by OrianaVenture** [comment]
Hi @Mistermycelium,

The Hildir items unlock once the player turns in the chest. When using private keys each player would have to individually turn in a chest. Players can check if they have access to the keys by using the "listprivatekeys" console commands and there will be the keys Hildir1, Hildir2, Hildir3 for each of the chests turned in. I tested to make sure it was still working and it appears to function correctly. Can you check that your players are turning in the chests and have these keys in their private lists? If you send me your config file I can also make sure the settings are set up as you would expect them to work.

If you have discord that is the fastest way to receive help from me, just mention this post if you reach out to me there. Otherwise I will check back for a response here as fast as possible.

**Comment by Mistermycelium** [comment]
I'm sorry for the bug report. The server crashed last night and after restarting it seems like it's all functional again. It looks like I have some work to do tracking down why the server is having issues.
