### ISSUE TITLE
[Compatibility concern] Logout tweaks player save data new usage might conflict with ServerCharacters

### ISSUE THREAD

**Issue by Magnacoder** [OrianaVenture/VentureValheim#23]
Hi there, 
Would the new version of https://github.com/OrianaVenture/VentureValheim/blob/master/LogoutTweaks/src/LogoutTweaks.cs (0.4.0) risk compatibility with servers using SmoothBrain's ServerCharacters? 

https://github.com/blaxxun-boop/ServerCharacters/blob/master/ServerCharacters/ClientSide.cs#L290 

I'm wondering if it's introducing bugs on my server that are hard to find because of both mods saving to the playersave and the way which blaxxun's retrieves serverside data somehow.

**Comment by OrianaVenture** [comment]
Hi Magnacoder,

If you were using an older version of my mod that used an external file to store the player data then it would not sync at all with server characters. I have since integrated saving the data directly to the player save file after the 0.4.0 update. If Server Characters is sending the whole save file it should include the custom data from this mod. Other mods use this custom data saving structure too, and I have not seen issues with those mods reported personally. From my understanding the custom data should be synced.

If there is a specific bug or issue you are trying to figure out please give more details and I can try to help further. I am fastest to respond on discord, so if you find me there just link to this issue.

**Comment by Magnacoder** [comment]
You're awesome. Thank you for your thorough and friendly reply!
