### ISSUE TITLE
Mining Caves Lock Terrain config conflicts with Sears Catalog

### ISSUE THREAD

**Issue by ZenDragonX** [OrianaVenture/VentureValheim#30]
When using the Lock Terrain feature of Mining Caves it causes Sears Catalog to break.

May I suggest breaking that lock terrain feature out into its own mod?  It's a fantastic idea but needs just a few small additional options: The hoe should still be able to level terrain.  Pickaxe could be limited to X meters down and hoe raising terrain to X meters up.  That way it isn't "locked" terrain instead it's limited terraforming so players don't cut a hole through a mountain but they could still level out an area for crops or a house foundation.  I just LOVE the concept but it's really obscure to find it in a mod called Mining Caves.  Separating the two would be nice, and also working with Sears Catalog. :) Great work!

**Comment by OrianaVenture** [comment]
Hi ZenDragonX,

The entire purpose for the mod was so that terrain changes could be disabled. That was the original idea and the caves are a byproduct of that fact. I understand people may not want to use this, so I made a configuration to enable and disable this. There is an additional config for excluding certain items like the Hoe if desired to only lock changes for certain objects.

What is broken with Sears Catalog? I have been using it just fine on my server with Mining Caves installed.
