### ISSUE TITLE
conflict between Logout Tweaks and Speedy Paths

### ISSUE THREAD

**Issue by nbusseneau** [OrianaVenture/VentureValheim#36]
Hey,

Noticed there's a conflict between Logout Tweaks and [Speedy Paths](https://thunderstore.io/c/valheim/p/Nextek/SpeedyPaths/): if you logout while the Speedy Paths buff is active (e.g. while standing on wood or stone), on login the Speedy Paths buff appears twice, with one of the buffs doing nothing but staying permanently, even if you walk away from wood / stone.

**Comment by nbusseneau** [comment]
I had a quick look at the code and I'm not sure why the buff is not ignored by Logout Tweaks though :/

**Comment by OrianaVenture** [comment]
I thought I had fixed the incompatibility in the 0.5.0 update. What version of the mods and game are you using?

**Comment by nbusseneau** [comment]
Yeah, from looking at the code added in 0.5.0 it makes no sense to me either why the status effect is picked up... Haven't investigated further.

Versions:
- Game: 0.217.46
- Logout Tweaks: 0.5.0
- SpeedyPaths: 1.0.8

**Comment by OrianaVenture** [comment]
Oh, I remember now. I couldn't fix that because the status effects from Speedy Paths aren't mimicking vanilla behavior and are added when Hud.instance.UpdateStatusEffects is called here [Speedy Paths Repo](https://github.com/NNaso/ValheimMods/blob/main/SpeedyPaths/SpeedyPaths.cs#L202). Which my mod calls here [Logout Tweaks Repo](https://github.com/OrianaVenture/VentureValheim/blob/master/LogoutTweaks/src/LogoutTweaks.cs#L199). I might be able to remove that line if the status effects are updating properly without it. Otherwise I have my own version of that mod called Need For Speed you can use in its place until it can be fixed.

**Comment by nbusseneau** [comment]
Good catch! Yeah it looks like `UpdateStatusEffects` is called in the main `Update` loop so I suspect it should be fine even without a manual call at load time.

Did see Need for Speed but I liked the Speedy Paths approach with a visible status effect better, makes it obvious to the user when a buff or debuff is applied 😅

**Comment by OrianaVenture** [comment]
This is fixed in version 0.5.1

**Comment by nbusseneau** [comment]
Thanks!
