### ISSUE TITLE
World Advancement Progression: `LockEquipment` blocks usage of poison arrows found in the Swamp's crypts

### ISSUE THREAD

**Issue by nbusseneau** [OrianaVenture/VentureValheim#40]
Hey,

With `LockEquipment = true` in World Advancement Progression's config, poison arrows found in the Swamp's crypts cannot be used, because their recipe requires obsidian from the Mountain biome.

I think poison arrows are the only instance of an item in Valheim's "intended progression" that you can find prior to finding the materials 🤔

**Comment by OrianaVenture** [comment]
To get around this servers can change the recipes of the items they want unlocked sooner. Currently I will not be implementing custom configurations for setting up locking since it adds another layer of complexity that makes it harder to maintain the mod. When the game exits early access I intend to add a feature to let people more fully control the locking system.

**Comment by nbusseneau** [comment]
Yeah I agree that adding a whole layer for that is not practical right now, however in this case I think since it's the sole item in that category, we don't really need a fully extensible mechanism. We could get away with just having special handling for it similar to the already existing exception for entrails with Meadows.

I will submit a PR, you can decide what you think about it.

**Comment by nbusseneau** [comment]
#41

**Comment by Jonny-Havoc** [comment]
@nbusseneau you should add this PR
